import{a as B,S as E,i as c}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",R="52629848-261c53034f3f85396bd8026ef";async function g(r,t=1,i=15){try{const{data:s}=await B.get(M,{params:{key:R,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}});return s}catch(s){throw console.error("Pixabay API error:",s),s}}const h=document.querySelector(".gallery"),y=document.querySelector(".loader"),$=new E(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function L(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:P,downloads:q})=>`
      <li class="list-item">
        <a href="${s}" class="item-img-link">
          <img class="gallery-img" src="${i}" alt="${e}" />
        </a>
        <div class="img-info-wrap">
          <div class="img-info"><p>Likes</p><p>${o}</p></div>
          <div class="img-info"><p>Views</p><p>${n}</p></div>
          <div class="img-info"><p>Comments</p><p>${P}</p></div>
          <div class="img-info"><p>Downloads</p><p>${q}</p></div>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function x(){h.innerHTML=""}function b(){y.classList.add("visible")}function v(){y.classList.remove("visible")}const S=document.querySelector(".form"),f=document.querySelector('button[type="submit"]'),I=document.querySelector('input[name="search-text"]'),p=document.querySelector(".load-more");let a=1,d="";const l=15;let u=0;S.addEventListener("submit",O);p.addEventListener("click",A);async function O(r){r.preventDefault();const t=I.value.trim();if(!t){c.error({message:"❌ Search field cannot be empty!",color:"red",position:"topRight",messageSize:"18",icon:!1,progressBar:!1});return}d=t,a=1,x(),m(),b(),f.disabled=!0;try{const i=await g(d,a,l);if(u=i.totalHits,!i.hits.length){c.error({message:"❌ Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"});return}L(i.hits),a*l<u&&w()}catch{c.error({message:"❌ Network Error",color:"red",position:"topRight"})}finally{S.reset(),v(),f.disabled=!1}}async function A(){a+=1,b(),m();try{const r=await g(d,a,l);L(r.hits),D(),a*l>=u?(m(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"})):w()}catch{c.error({message:"❌ Error loading more images!",color:"red",position:"topRight"})}finally{v()}}function w(){p.classList.remove("hidden")}function m(){p.classList.add("hidden")}function D(){var t;const r=(t=document.querySelector(".gallery .list-item"))==null?void 0:t.getBoundingClientRect();if(r){const i=r.height;window.scrollBy({top:i*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
